### ISSUE TITLE
search.php doesn't work

### ISSUE THREAD

**Issue by SergioZgz** [wsjmnh/music163-API#1]
Fixed :) forget it

**Comment by jh97uk** [comment]
Mine just outputs a long string of randomized characters! What did you do to make yours work?

**Comment by hahuy** [comment]
Can you help me decode the string results? thanks!!!

**Comment by wsjmnh** [comment]
The code not working anymore.

Demo site I have changed.
Please refer this http://moonlib.com/606.html

I'm not the author btw.
